### ISSUE TITLE
Compiling process doesn't give "glad" library?

### ISSUE THREAD

**Issue by BinarryCode** [bedhededdy/nescle#1]
Self explanatory, the CMake file gave an error for it.
also I had to install it differently from the readme:
`powershell -ExecutionPolicy Bypass -File install.ps1`
`mkdir build`
`cd build`
`cmake ..`

(also kinda unrelated complaint but can you put the .c and .h files in the root of the repo in a separate folder so its easier to read)

**Comment by bedhededdy** [comment]
NESCLE is still in the early stages of development and is not recommended for general use. When I determine the emulator is in a basic functional state, I will create a 1.0 release at which point I would recommend trying it out. The audio in particular is nowhere near being usable. I am also lacking proper implementations of MMC1 and MMC3, which means a huge portion of games are not playable. I am currently in the process of rewriting NESCLE to use OpenGL for the rendering instead of SDL_Renderer so that I can use the Multi-Viewport functionality of ImGui. I did forget to include Glad in the install script, so thank you for pointing that out. I will also eventually move the source code to a src directory at a later date. I appreciate you taking a look, and hope you bear with me as I get NESCLE off the ground!

**Comment by bedhededdy** [comment]
Apologies that it took so long for me to get around to this; I am a student and I was busy with assignments and midterms. Instructions for building have been massively simplified and I have added instructions for how to install glad. There is no way that I know of to download a specific glad configuration, as they are generated dynamically according to the specification you provide the web client. Therefore, you must install it manually. Also, as you suggested, all the source files have been added to a separate src directory. At this time, I can recommend that you try out NESCLE as the audio is no longer ear piercing (although it is incomplete) and games that use Mappers 0, 2, 3, 7, should be fully playable. Thanks for bearing with me, and I hope you enjoy giving NESCLE a try! Don't hesitate to contact me if you encounter any more difficulties!
